### ISSUE TITLE
eop:codeSpace attribute of eop:wrsLatitudeGrid

### ISSUE THREAD

**Issue by lmar76** [stcorp/procsim#16]
eop:codeSpace attribute of eop:wrsLatitudeGrid is wrong. Correct attribute name is `codeSpace` (i.e. without `eop` prefix). E.g.:

```xml
<eop:wrsLatitudeGrid codeSpace="urn:esa:eop:Biomass:frames">2</eop:wrsLatitudeGrid>
```

**Comment by pe1obw** [comment]
Fixed in master
