### ISSUE TITLE
Getting the number of a slice by its central time

### ISSUE THREAD

**Issue by mivermeu** [stcorp/procsim#20]
Are we sure getting the number of a slice by its central time always works?

Consider a short fragment, with phenomenon time from TsliceNstart - 2 to TsliceNstart + 1. I think that this fragment can be in either slice N or in slice N-1 ...

_Originally posted by @pe1obw in https://github.com/stcorp/procsim/pull/17#discussion_r762897366_

**Comment by lmar76** [comment]
In my opinion:
- if `enable_slicing` is `true`:
    - if `slice_minimum_duration` is set (to enable merging):
        - if the two resulting fragments of slice are shorter than this value:
            - a single fragment is generated and the slice id is the one of the greater slice
        - else: two fragments of slice are generated, each one with its own slice id
    - else: two fragments of slice are generated, each one with its own slice id
- else: the fragment is not sliced and I think that the slice number doesn't make sense.
