### ISSUE TITLE
Support for RAW___HKTM

### ISSUE THREAD

**Issue by lmar76** [stcorp/procsim#23]
Even if RAW___HKTM products are not involved in the data processing, they are ingested, by the CPF, from the acquisition facility and disseminated to the master archive.

To facilitate the overall end-to-end PDGS testing, it may be worth to add to Procsim the capability to generate "dummy" RAW___HKTM products. This feature may be used, in the test preparation phase, to generate such products.

These products have the same structure as the other RAW (see the applicable BIOMASS RAW Product Format Definition document).

Can you please evaluate the feasibility of this additional feature?

**Comment by mivermeu** [comment]
We have implemented this feature in #26. HKTM files are now generated alongside other RAW files. You can set the following fields unique to HKTM headers in the scenario:
- num_tf
- num_tf_erroneous
- num_tf_corrupt

These are set analogously to the num_isp settings. If unset, they default to 0.

**Comment by lmar76** [comment]
Tested
