### ISSUE TITLE
No scenario with matching outputs found

### ISSUE THREAD

**Issue by lmar76** [stcorp/procsim#3]
Level 0 step 2 processing has been executed as follows:

```
% /opt/pnode/bin/procsim -t l0pfs2.sh -j JobOrder.WD-TOM_TDS-MM-DTID8202-L0PFS2.xml /opt/pnode/etc/l0-scenarios.json
2021-07-22T14:17:11.640720    Unknown [0000052611]: [E] No scenario with matching outputs found for l0pfs2.sh.
2021-07-22T14:17:11.640810    Unknown [0000052611]: [I] Terminate with code 1
```

The error seems due to the fact that the outputs defined in the scenario file [l0-scenarios.json.zip](https://github.com/stcorp/procsim/files/6862133/l0-scenarios.json.zip), see scenario name: "TOM_TDS - MM - DTID 8282 - L0PFS2", are a subset of the output products reported in [JobOrder.WD-TOM_TDS-MM-DTID8202-L0PFS2.xml.zip](https://github.com/stcorp/procsim/files/6862144/JobOrder.WD-TOM_TDS-MM-DTID8202-L0PFS2.xml.zip). If I try to update the Job Order leaving only S1_RAW__0S and S1_RAWP_0M, the processing is successfully completed.

Please note that the outputs, reported in the job order for each task, represent all the possible outputs of that task. This does not imply that all of them must be generated. This is the case of L0 step 2: in this case, the PF does not know if the output product will be S1_RAW__0S, S2_RAW__0S or S3_RAW__0S because this depends on the input data content, read by the processor.

**Comment by mivermeu** [comment]
It was previously required that outputs defined in a scenario exactly matched the outputs in a task's job order. Commit 838f454 changes this behaviour to allow for scenario outputs to comprise a subset of the job order's outputs.

The files attached to this issue are of an old format and refer to data that I don't have, but I reproduced the issue and tested the solution by adding a dummy output to a job order previously known to work in combination with a certain scenario. Where this test case previously failed, it now works as expected. All scenario outputs must of course still be represented in the job order's list of possible outputs.
