### ISSUE TITLE
Support for multiple data takes 

### ISSUE THREAD

**Issue by lmar76** [stcorp/procsim#37]
In our test scenario, we need to generate Biomass products related to different data takes. E.g. in the L0 step 2 simulation, we have, for each data take, one scenario defined as follows:

```json
{
    "name": "SM 6632654 L0PFStep2",
    "file_name": "L0PFStep2",
    "processor_name": "L0PFStep2",
    "processor_version": "01.00",
    "task_name": "L0PFStep2",
    "task_version": "01.00",
    "log_level": "debug",
    "data_takes": [
        {
            "data_take_id": 6632654,
            "start": "2017-02-25T09:46:04.620306Z",
            "stop": "2017-02-25T09:58:34.884917Z",
            "swath": "S3",
            "operational_mode": "SM"
        }
    ],
    "begin_end_position_from_toi": true,
    "mission_phase": "INTERFEROMETRIC",
    "global_coverage_id": "1",
    "major_cycle_id": "2",
    "repeat_cycle_id": "1",
    "track_nr": "17",
    "num_l0_lines": "2233530,2233530",
    "num_l0_lines_corrupt": "0,0",
    "num_l0_lines_missing": "0,0",
    "outputs": [
        {
            "type": "S3_RAW__0S"
        },
        {
            "type": "S3_RAWP_0M"
        }
    ]
}
```

The reason for having one scenario for each data take is that the parameters change from one data take to another, e.g.: `repeat_cycle_id`, `track_number`.

As far as I understood from my testing activities, it is not possible to include _in the same configuration file_ two or more scenarios having the same: `file_name`, `processor_name`, `processor_version`, `task_name`, `task_version` because Procsim selects the proper scenario using these parameters that should be unique in the file (otherwise it selects the first one that matches them).

This forces us to create a configuration file for each data take to be simulated and to change it each time. This is fine if we need to execute "manual" tests but it becomes very tricky if we need to execute tests with the CPF which automatically starts processing activities every time a new input is available.

For this reason I would like to ask you to analyze the possibility to define the configuration parameters at data take level, e.g.:

```
{
    "name": "...",
    "file_name": "L0PFStep2",
    "processor_name": "L0PFStep2",
    "processor_version": "01.00",
    "task_name": "L0PFStep2",
    "task_version": "01.00",
    "log_level": "debug",
    "data_takes": [
        {
            "data_take_id": 6632654,
            "start": "2017-02-25T09:46:04.620306Z",
            "stop": "2017-02-25T09:58:34.884917Z",
            "swath": "S3",
            "operational_mode": "SM",
            "mission_phase": "INTERFEROMETRIC",
            "global_coverage_id": "1",
            "major_cycle_id": "2",
            "repeat_cycle_id": "1",
            "track_nr": "17",
            "num_l0_lines": "2233530,2233530",
            "num_l0_lines_corrupt": "0,0",
            "num_l0_lines_missing": "0,0"
            [...]
        },
        {
            "data_take_id": ....,
            "start": ".....",
            "stop": ".....",
            "swath": "S3",
            "operational_mode": "SM",
            "mission_phase": "INTERFEROMETRIC",
            "global_coverage_id": "1",
            "major_cycle_id": "4",
            "repeat_cycle_id": "3",
            "track_nr": "25",
            "num_l0_lines": "...,...",
            "num_l0_lines_corrupt": "0,0",
            "num_l0_lines_missing": "0,0"
            [...]
        },
    ],
    "begin_end_position_from_toi": true,
    "outputs": [
        {
            "type": "S3_RAW__0S"
        },
        {
            "type": "S3_RAWP_0M"
        }
    ]
```

In this case, Procsim would only need to compare the begin/end position of the output product to the data take start stop time to "understand" which is the applicable data take and apply the related parameters.

This would allow us to create a single configuration file with the proper information for each data take.

Please note that this is just an idea. Let us know if you have a better one to associate a set of parameters to each data take.

**Comment by pe1obw** [comment]
When multiple datatakes are defined in the scenario, as in your second example, a datatake is selected based on the begin/end position, originating either from the job order, a 'meta data source' product, or from the scenario.

Also, it is already possible to specify (almost) all parameters on the datatake level. Exception are a few common parameters, such as the output path and the 'begin_end_position_from_toi' flag. 

So, I'd expect your second example to work with the current procsim. If not, could you provide us with the job order file? 
Or did I understood something wrong?

**Comment by lmar76** [comment]
I did a test defining the following parameters at scenario level (i.e. the root level of the scenario):
- mission_phase
- global_coverage_id
- major_cycle_id
- repeat_cycle_id
- track_number

The parameters value are correctly reported in the output file names and MPHs with the exception of dataTakeID (set to `None`) and track number (set to 0):

```
outputs.old/S3_SCS__1S/BIO_S3_SCS__1S_20170225T094604_20170225T094620_I_G01_M02_C01_T000_F283_01_BQ7BW0
outputs.old/S3_DGM__1S/BIO_S3_DGM__1S_20170225T094604_20170225T094620_I_G01_M02_C01_T000_F283_01_BQ7BW0
outputs.old/S3_SCS__1M/BIO_S3_SCS__1M_20170225T094604_20170225T094620_I_G01_M02_C01_T000_F283_01_BQ7BW0
```

I did an additional test moving the definition of the same parameters at data take level:

```json
                {
                    "data_take_id": 6632654,
                    "start": "2017-02-25T09:46:04.620306Z",
                    "stop": "2017-02-25T09:58:34.884917Z",
                    "swath": "S3",
                    "operational_mode": "SM",
                    "mission_phase": "INTERFEROMETRIC",
                    "global_coverage_id": "1",
                    "major_cycle_id": "2",
                    "repeat_cycle_id": "1",
                    "track_number": "17"
                }
```

Procsim raised the following error:

```
2022-06-21T15:56:45.104145+00:00 ESR01104747 L1_P 01.00 L1_P [0000058733]: [E] mission_phase must be set
```

So, I moved the `mission_phase` parameter back to the scenario "root" level and executed the test again. dataTakeID  and track number are still set to `None` and 0 respectively. In addition, the specified values of global coverage id, major cycle id repeat cycle id are not reported in the file names and in the MPH:

```
outputs/S3_SCS__1S/BIO_S3_SCS__1S_20170225T094604_20170225T094620_I_G___M01_C___T000_F283_01_BQ7DR3
outputs/S3_DGM__1S/BIO_S3_DGM__1S_20170225T094604_20170225T094620_I_G___M01_C___T000_F283_01_BQ7DR3
outputs/S3_SCS__1M/BIO_S3_SCS__1M_20170225T094604_20170225T094620_I_G___M01_C___T000_F283_01_BQ7DR3
```

Please find attached the working directory containing the job order, the scenario configuration and output directories of both tests: [wdir-l1-f283.zip](https://github.com/stcorp/procsim/files/8950593/wdir-l1-f283.zip)

**Comment by mivermeu** [comment]
With PR #50, data takes should be supported properly. For all products that require a `dataTakeId` node, you can now specify data take parameters in two ways:
- In the root of the scenario.
- In a `"data_takes"` list element.

You can also specify any other parameters in the `"data_takes"` list elements and they will overwrite the root scenario parameters for that data take.

As mentioned elsewhere, the track number being set to 0 is due to the use of the `"track_number"` parameter instead of `"track_nr"`.

Let us know if things work as expected for you!
